- title: Postdoctoral Fellowships 
  venue: Auburn's 2026 Research Symposium
  location: Auburn, AL
  description: "Panelist at Auburn's 2026 Research Symposium for graduate students interested in postdoctoral positions."
  type: Panel
  years: Spring 2026
- title: Macaulay2 Internals
  type: Volunteer
  location: Online
  description: "Work on internals of the M2 software and developing the vscode interface."
  years: 2024-
  highlight: true
- title: Organizing Conferences Aimed at Graduate Students
  venue: UW Madison
  location: Madison, WI
  type: Panel
  description: "Panelist on a discussion about organizing conferences held by the UW Madison math department."
  years: Spring 2024
- title: UW Madison Directed Reading Program 
  type: Mentor
  url: https://sites.google.com/site/uwmadisondrp/
  location: Madison, WI
  years: Spring 2024
  description: Led a group of students in reading Stillwell's "Mathematics and its History".
  short-description: Led a group of students in reading Stillwell's "Mathematics and its History".
- title: Madison Experimental Mathematics Lab
  type: Mentor
  location: Madison, WI
  years: Fall 2022, Spring 2023
  description: Directed advanced 4 undergraduates on a computationally focused research project concerning identifiable linear compartmental models.
  short-description: Directed advanced 4 undergraduates on a computationally focused research project concerning identifiable linear compartmental models.
- title: Madison Undergraduate Mentoring Program
  type: Mentor
  location: Madison, WI
  years: Fall 2022
  description: Met with a group of undergraduate math majors to give advice about how to navigate their undergrad degree, plan for grad school apps, and think about REUs and other opportunities.
- title: Madison Graduate Mentoring Program
  type: Mentor
  location: Madison, WI
  years: 2022-2023
  description: Helped orient new PhD students into the PhD program at UW Madison.
  hide: true
- title: WISCIENCE Public Service Fellow
  type: Volunteer
  url: https://wiscience.wisc.edu/program/public-service-fellows
  location: Madison, WI
  years: 2021
  description: Met and discussed best ways to engage with the public and worked with a community partner on a web project to make arXiv easier to navigate.
- title: First Generation Student Success
  type: Mentor
  url: https://firstgensuwmadison.wixsite.com/fgss
  location: Madison, WI
  years: Fall 2020, Spring 2021
  description: "FGSS links first-generation college students to first generation graduate and faculty mentors for monthly meetings. "
  short-description: "FGSS links first-generation college students to first generation graduate and faculty mentors for monthly meetings. "
  highlight: true
- title: AMS Fall Central Sectional
  type: Volunteer
  years: Sep 2019
  location: Madison, WI
  description: "Signed in attendees to the 3-day AMS Fall central sectional meeting."
- title: CofC Student Ambassador
  type: Volunteer
  years: 2019
  location: Charleston, SC
  description: Select group of 9 students who have demonstrated outstanding academic achievement and exemplar student leadership. Represent the School of Sciences and Mathematics at College of Charleston to incoming students and other interest groups.
  hide: true
- title: Student Vice President of Phi Kappa Phi
  type: Volunteer
  years: 2017-2019
  location: Charleston, SC
  description: Met with board to coordinate volunteer opportunities and promote education throughout the College of Charleston campus. Helped organize events on campus for Phi Kappa Phi members. 
- title: AMS Spring Southeastern Sectional Meeting
  type: Volunteer
  years: Mar 2017
  location: Charleston, SC
  description: "Signed in attendees to the 3-day AMS Spring southeastern sectional meeting."
- title: College of Charleston Math Meet
  type: Volunteer
  years: 2016-2018
  url: https://mathmeet.cofc.edu/
  location: Charleston, SC
  description: "Volunteered to oversee various parts of the planned activities including judging timed sprints and signing students in."
- title: Trident Literacy Association
  type: Volunteer
  years: 2015-2016
  url: https://tridentlit.org/
  location: Charleston, SC
  description: "Helped weekly to prepare nontraditional students for their GED."
  short-description: "Helped weekly to prepare nontraditional students for their GED."