name: Not Found Bot

on:
  schedule:
    - cron: "0 5 1 * *"
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Fix links
        uses: tmcw/notfoundbot@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          content-folder: .
